version: 2.1

jobs:
  build: # this can be any name you choose
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - checkout

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7

      - run:
          name: Build app
          command: |
            pnpm install
            pnpm build
      
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

      - persist_to_workspace:
          paths:
            - "."
          root: ~/project

  test: # this can be any name you choose
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project/

      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7

      - run:
          name: Test app
          command: pnpm test

workflows:
    build:
      jobs:
        - build
        - test:
            requires:
              - build