name: Branch output

on:
  push:
    branches: ["docker-deploy"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1
      - name: Echo branch name
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          echo ${GITHUB_REF#refs/heads/}

      - name: Uesh
        run: echo ${{ steps.extract_branch.outputs.branch }}

